name: build

on:
  push:
    branches: [main, native-bash-rewrite]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build
